### ISSUE TITLE
[AXONIQ-2000] Invalid sequence number 0 - RegisterProcessDefinitionCommand

### ISSUE THREAD

**Issue by pschalk** [holunda-io/camunda-bpm-taskpool#255]
### Steps to reproduce

* camunda-bpm-taskpool version: 2.0.7
* Camunda BPM version: 7.12.0
* JDK version:  11
* Steps: (what exactly are you doing with the above reproducer?)

Running Axonserver + persisted backend -> Start backend with camunda + some dummy process. (Always the same process)
Not sure if important, but I think when deploying the process the first time, axon server was not used (so just in memory axon was used)

### Expected behaviour

RegisterProcessDefinitionCommand is just fired once, no error is thrown. 

### Actual behaviour

Following error occurs multiple times when starting the backend: 

```
2020-09-11 15:36:17.643 ERROR 23687 --- [grpc-default-executor-0] i.h.c.taskpool.sender.CommandSender      : SENDER-006: Sending command GenericCommandMessage{payload={RegisterProcessDefinitionCommand(processDefinitionId=Mehrarbeitsantrag:4:8bd622f4-c6b8-11ea-8ff7-005056a3bb3c, processDefinitionKey=Mehrarbeitsantrag, processDefinitionVersion=4, applicationName=selfservice-core, processName=Mehrarbeitsantrag anlegen, processVersionTag=null, processDescription=null, formKey=null, startableFromTasklist=true, candidateStarterUsers=[], candidateStarterGroups=[])}, metadata={}, messageIdentifier='a8317c71-4a9d-49e1-8bec-a95ea9b35880', commandName='io.holunda.camunda.taskpool.api.task.RegisterProcessDefinitionCommand'} resulted in error

org.axonframework.commandhandling.CommandExecutionException: OUT_OF_RANGE: [AXONIQ-2000] Invalid sequence number 0 for aggregate Mehrarbeitsantrag:4:8bd622f4-c6b8-11ea-8ff7-005056a3bb3c, expected 1
        at org.axonframework.axonserver.connector.ErrorCode.lambda$static$10(ErrorCode.java:88) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        at org.axonframework.axonserver.connector.ErrorCode.convert(ErrorCode.java:182) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        at org.axonframework.axonserver.connector.command.CommandSerializer.deserialize(CommandSerializer.java:157) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        at org.axonframework.axonserver.connector.command.AxonServerCommandBus$1.onNext(AxonServerCommandBus.java:313) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        at org.axonframework.axonserver.connector.command.AxonServerCommandBus$1.onNext(AxonServerCommandBus.java:306) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:429) ~[grpc-stub-1.22.1.jar!/:1.22.1]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) ~[grpc-api-1.22.1.jar!/:1.22.1]
        at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33) ~[grpc-api-1.22.1.jar!/:1.22.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:596) ~[grpc-core-1.22.1.jar!/:1.22.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:581) ~[grpc-core-1.22.1.jar!/:1.22.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.22.1.jar!/:1.22.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.22.1.jar!/:1.22.1]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.axonframework.axonserver.connector.command.AxonServerRemoteCommandHandlingException: An exception was thrown by the remote message handling component: OUT_OF_RANGE: [AXONIQ-2000] Invalid sequence number 0 for aggregate Mehrarbeitsantrag:4:8bd622f4-c6b8-11ea-8ff7-005056a3bb3c, expected 1
Caused by OUT_OF_RANGE: [AXONIQ-2000] Invalid sequence number 0 for aggregate Mehrarbeitsantrag:4:8bd622f4-c6b8-11ea-8ff7-005056a3bb3c, expected 1
        at org.axonframework.axonserver.connector.ErrorCode.lambda$static$10(ErrorCode.java:86) ~[axon-server-connector-4.3.1.jar!/:4.3.1]
        ... 14 common frames omitted
```

So looks like the command is fired every time when starting the server.

**Comment by zambrovski** [comment]
Can't reproduce this issue. The parse listener is executed only on deployment. Maybe your setup lets you re-deploy the same process every time? Please check the scenario with distributed axon.

**Comment by zambrovski** [comment]
I could reproduce it again! So, I'll reopen the issue again!
